// Auto-generated by @skippy/cache - do not edit manually

import { z } from 'zod';

export const ArcSchema = z.object({
  id: z.string(),
  name: z.string(),
  description: z.string(),
  icon: z.string(),
  image: z.string(),
  created_at: z.string(),
  updated_at: z.string(),
});

export type Arc = z.infer<typeof ArcSchema>;
