// Auto-generated by @skippy/cache - do not edit manually

import { z } from 'zod';

export const EventSchema = z.object({
  name: z.string(),
  map: z.string(),
  icon: z.string(),
  startTime: z.number(),
  endTime: z.number(),
});

export type Event = z.infer<typeof EventSchema>;
