// Auto-generated by @skippy/cache - do not edit manually

import { z } from 'zod';

export const ItemStatBlockSchema = z
  .object({
    range: z.number(),
    value: z.number(),
    damage: z.number(),
    health: z.number(),
    radius: z.number(),
    shield: z.number(),
    weight: z.number(),
    agility: z.number(),
    arcStun: z.number(),
    healing: z.number(),
    stamina: z.number(),
    stealth: z.number(),
    useTime: z.number(),
    duration: z.number(),
    fireRate: z.number(),
    stability: z.number(),
    stackSize: z.number(),
    damageMult: z.number(),
    raiderStun: z.number(),
    weightLimit: z.number(),
    augmentSlots: z.number(),
    healingSlots: z.number(),
    magazineSize: z.number(),
    reducedNoise: z.number(),
    shieldCharge: z.number(),
    backpackSlots: z.number(),
    quickUseSlots: z.number(),
    damagePerSecond: z.number(),
    movementPenalty: z.number(),
    safePocketSlots: z.number(),
    damageMitigation: z.number(),
    healingPerSecond: z.number(),
    reducedEquipTime: z.number(),
    staminaPerSecond: z.number(),
    increasedADSSpeed: z.number(),
    increasedFireRate: z.number(),
    reducedReloadTime: z.number(),
    illuminationRadius: z.number(),
    increasedEquipTime: z.number(),
    reducedUnequipTime: z.number(),
    shieldCompatibility: z.string(),
    increasedUnequipTime: z.number(),
    reducedVerticalRecoil: z.number(),
    increasedBulletVelocity: z.number(),
    increasedVerticalRecoil: z.number(),
    reducedMaxShotDispersion: z.number(),
    reducedPerShotDispersion: z.number(),
    reducedDurabilityBurnRate: z.number(),
    reducedRecoilRecoveryTime: z.number(),
    increasedRecoilRecoveryTime: z.number(),
    reducedDispersionRecoveryTime: z.number(),
  })
  .partial();
export const ItemLocationSchema = z.object({
  id: z.string(),
  map: z.string(),
});
export const ItemGuideLinkSchema = z.object({
  url: z.string(),
  label: z.string(),
});
export const ItemSchema = z.object({
  id: z.string(),
  name: z.string(),
  description: z.string(),
  item_type: z.string(),
  loadout_slots: z.array(z.string()),
  icon: z.string().nullable(),
  rarity: z.string().nullable(),
  value: z.number(),
  workbench: z.string().nullable(),
  stat_block: ItemStatBlockSchema,
  flavor_text: z.string().nullable(),
  subcategory: z.string().nullable(),
  created_at: z.string(),
  updated_at: z.string(),
  shield_type: z.string().nullable(),
  loot_area: z.string().nullable(),
  sources: z.null().nullable(),
  ammo_type: z.string().nullable(),
  locations: z.array(ItemLocationSchema),
  guide_links: z.array(ItemGuideLinkSchema),
  game_asset_id: z.number().nullable(),
});

export type ItemStatBlock = z.infer<typeof ItemStatBlockSchema>;
export type ItemLocation = z.infer<typeof ItemLocationSchema>;
export type ItemGuideLink = z.infer<typeof ItemGuideLinkSchema>;
export type Item = z.infer<typeof ItemSchema>;
