// Auto-generated by @skippy/cache - do not edit manually

import { z } from 'zod';

export const QuestGrantedItemItemSchema = z.object({
  id: z.string(),
  icon: z.string(),
  name: z.string(),
  rarity: z.string(),
  item_type: z.string(),
});
export const QuestGrantedItemSchema = z.object({
  id: z.string(),
  item: QuestGrantedItemItemSchema,
  item_id: z.string(),
  quantity: z.number(),
});
export const QuestLocationSchema = z.object({
  x: z.number().optional(),
  y: z.number().optional(),
  map: z.string(),
  id: z.string().optional(),
});
export const QuestGuideLinkSchema = z.object({
  url: z.string(),
  label: z.string(),
});
export const QuestPositionSchema = z.object({
  x: z.number(),
  y: z.number(),
});
export const QuestRequiredItemItemSchema = z.object({
  id: z.string(),
  icon: z.string(),
  name: z.string(),
  rarity: z.string(),
  item_type: z.string(),
});
export const QuestRequiredItemSchema = z.object({
  id: z.string(),
  item: QuestRequiredItemItemSchema,
  item_id: z.string(),
  quantity: z.number(),
});
export const QuestRewardItemSchema = z.object({
  id: z.string(),
  icon: z.string(),
  name: z.string(),
  rarity: z.string(),
  item_type: z.string(),
});
export const QuestRewardSchema = z.object({
  id: z.string(),
  item: QuestRewardItemSchema,
  item_id: z.string(),
  quantity: z.string(),
});
export const QuestSchema = z.object({
  id: z.string(),
  name: z.string(),
  objectives: z.array(z.string()),
  xp: z.number(),
  granted_items: z.array(QuestGrantedItemSchema),
  created_at: z.string(),
  updated_at: z.string(),
  locations: z.array(QuestLocationSchema),
  marker_category: z.string().nullable(),
  image: z.string(),
  guide_links: z.array(QuestGuideLinkSchema),
  trader_name: z.string(),
  sort_order: z.number(),
  position: QuestPositionSchema,
  required_items: z.array(QuestRequiredItemSchema),
  rewards: z.array(QuestRewardSchema),
});

export type QuestGrantedItemItem = z.infer<typeof QuestGrantedItemItemSchema>;
export type QuestGrantedItem = z.infer<typeof QuestGrantedItemSchema>;
export type QuestLocation = z.infer<typeof QuestLocationSchema>;
export type QuestGuideLink = z.infer<typeof QuestGuideLinkSchema>;
export type QuestPosition = z.infer<typeof QuestPositionSchema>;
export type QuestRequiredItemItem = z.infer<typeof QuestRequiredItemItemSchema>;
export type QuestRequiredItem = z.infer<typeof QuestRequiredItemSchema>;
export type QuestRewardItem = z.infer<typeof QuestRewardItemSchema>;
export type QuestReward = z.infer<typeof QuestRewardSchema>;
export type Quest = z.infer<typeof QuestSchema>;
