// Auto-generated by @skippy/cache - do not edit manually

import { z } from 'zod';

export const TraderItemSchema = z.object({
  id: z.string(),
  icon: z.string(),
  name: z.string(),
  value: z.number(),
  rarity: z.string(),
  item_type: z.string(),
  description: z.string(),
  trader_price: z.number(),
});
export const TraderSchema = z.object({
  name: z.string(),
  items: z.array(TraderItemSchema),
});

export type TraderItem = z.infer<typeof TraderItemSchema>;
export type Trader = z.infer<typeof TraderSchema>;
