// Auto-generated by @skippy/cache - do not edit manually

export interface Arc {
  id: string;
  name: string;
  description: string;
  icon: string;
  image: string;
  created_at: string;
  updated_at: string;
}
