// Auto-generated by @skippy/cache - do not edit manually

export interface ItemStatBlock {
  range: number;
  value: number;
  damage: number;
  health: number;
  radius: number;
  shield: number;
  weight: number;
  agility: number;
  arcStun: number;
  healing: number;
  stamina: number;
  stealth: number;
  useTime: number;
  duration: number;
  fireRate: number;
  stability: number;
  stackSize: number;
  damageMult: number;
  raiderStun: number;
  weightLimit: number;
  augmentSlots: number;
  healingSlots: number;
  magazineSize: number;
  reducedNoise: number;
  shieldCharge: number;
  backpackSlots: number;
  quickUseSlots: number;
  damagePerSecond: number;
  movementPenalty: number;
  safePocketSlots: number;
  damageMitigation: number;
  healingPerSecond: number;
  reducedEquipTime: number;
  staminaPerSecond: number;
  increasedADSSpeed: number;
  increasedFireRate: number;
  reducedReloadTime: number;
  illuminationRadius: number;
  increasedEquipTime: number;
  reducedUnequipTime: number;
  shieldCompatibility: string;
  increasedUnequipTime: number;
  reducedVerticalRecoil: number;
  increasedBulletVelocity: number;
  increasedVerticalRecoil: number;
  reducedMaxShotDispersion: number;
  reducedPerShotDispersion: number;
  reducedDurabilityBurnRate: number;
  reducedRecoilRecoveryTime: number;
  increasedRecoilRecoveryTime: number;
  reducedDispersionRecoveryTime: number;
}

export interface ItemLocation {
  id: string;
  map: string;
}

export interface ItemGuideLink {
  url: string;
  label: string;
}

export interface Item {
  id: string;
  name: string;
  description: string;
  item_type: string;
  loadout_slots: string[];
  icon: string;
  rarity: string;
  value: number;
  workbench: null;
  stat_block: ItemStatBlock;
  flavor_text: string;
  subcategory: string;
  created_at: string;
  updated_at: string;
  shield_type: string;
  loot_area: string;
  sources: null;
  ammo_type: string;
  locations: ItemLocation[];
  guide_links: ItemGuideLink[];
  game_asset_id: number;
}
