// Auto-generated by @skippy/cache - do not edit manually

export interface QuestPosition {
  x: number;
  y: number;
}

export interface Quest {
  id: string;
  name: string;
  objectives: string[];
  xp: number;
  granted_items: unknown[];
  created_at: string;
  updated_at: string;
  locations: unknown[];
  marker_category: null;
  image: string;
  guide_links: object[];
  trader_name: string;
  sort_order: number;
  position: QuestPosition;
  required_items: unknown[];
  rewards: object[];
}
