// Auto-generated by @skippy/cache - do not edit manually

export interface QuestGrantedItemItem {
  id: string;
  icon: string;
  name: string;
  rarity: string;
  item_type: string;
}

export interface QuestGrantedItem {
  id: string;
  item: QuestGrantedItemItem;
  item_id: string;
  quantity: number;
}

export interface QuestLocation {
  x?: number;
  y?: number;
  map: string;
  id?: string;
}

export interface QuestGuideLink {
  url: string;
  label: string;
}

export interface QuestPosition {
  x: number;
  y: number;
}

export interface QuestRequiredItemItem {
  id: string;
  icon: string;
  name: string;
  rarity: string;
  item_type: string;
}

export interface QuestRequiredItem {
  id: string;
  item: QuestRequiredItemItem;
  item_id: string;
  quantity: number;
}

export interface QuestRewardItem {
  id: string;
  icon: string;
  name: string;
  rarity: string;
  item_type: string;
}

export interface QuestReward {
  id: string;
  item: QuestRewardItem;
  item_id: string;
  quantity: string;
}

export interface Quest {
  id: string;
  name: string;
  objectives: string[];
  xp: number;
  granted_items: QuestGrantedItem[];
  created_at: string;
  updated_at: string;
  locations: QuestLocation[];
  marker_category: null;
  image: string;
  guide_links: QuestGuideLink[];
  trader_name: string;
  sort_order: number;
  position: QuestPosition;
  required_items: QuestRequiredItem[];
  rewards: QuestReward[];
}
