// Auto-generated by @skippy/cache - do not edit manually

export interface TraderItem {
  id: string;
  icon: string;
  name: string;
  value: number;
  rarity: string;
  item_type: string;
  description: string;
  trader_price: number;
}

export interface Trader {
  name: string;
  items: TraderItem[];
}
