import { describe, test, expect } from 'vitest';
import {
  inferZodType,
  OBJECT_MARKER,
  OBJECT_ARRAY_MARKER,
  generateZodSchema,
} from '../src/generate-zod-schemas';

describe('inferZodType', () => {
  test('infers string type', () => {
    expect(inferZodType('hello')).toBe('z.string()');
  });

  test('infers number type', () => {
    expect(inferZodType(42)).toBe('z.number()');
    expect(inferZodType(3.14)).toBe('z.number()');
  });

  test('infers boolean type', () => {
    expect(inferZodType(true)).toBe('z.boolean()');
    expect(inferZodType(false)).toBe('z.boolean()');
  });

  test('infers null type', () => {
    expect(inferZodType(null)).toBe('z.null()');
  });

  test('infers primitive array types', () => {
    expect(inferZodType(['a', 'b'])).toBe('z.array(z.string())');
    expect(inferZodType([1, 2, 3])).toBe('z.array(z.number())');
    expect(inferZodType([true, false])).toBe('z.array(z.boolean())');
  });

  test('returns z.unknown() for empty array', () => {
    expect(inferZodType([])).toBe('z.array(z.unknown())');
  });

  test('returns object marker for objects', () => {
    expect(inferZodType({ key: 'value' })).toBe(OBJECT_MARKER);
  });

  test('returns object array marker for array of objects', () => {
    expect(inferZodType([{ id: 1 }])).toBe(OBJECT_ARRAY_MARKER);
  });
});

describe('generateZodSchema', () => {
  test('generates schema with simple fields', () => {
    const items = [{ id: '1', name: 'Test', value: 100 }];

    const result = generateZodSchema('Item', items);

    expect(result).toContain("import { z } from 'zod';");
    expect(result).toContain('export const ItemSchema = z.object({');
    expect(result).toContain('id: z.string()');
    expect(result).toContain('name: z.string()');
    expect(result).toContain('value: z.number()');
    expect(result).toContain('export type Item = z.infer<typeof ItemSchema>;');
  });

  test('generates optional fields when not in all items', () => {
    const items = [
      { id: '1', name: 'Test' },
      { id: '2', name: 'Test2', extra: 'field' },
    ];

    const result = generateZodSchema('Item', items);

    expect(result).toContain('id: z.string()');
    expect(result).toContain('extra: z.string().optional()');
  });

  test('generates nested schema for objects', () => {
    const items = [
      {
        id: '1',
        stat_block: { damage: 50, health: 100 },
      },
    ];

    const result = generateZodSchema('Item', items);

    expect(result).toContain('export const ItemStatBlockSchema = z.object({');
    expect(result).toContain('damage: z.number()');
    expect(result).toContain('health: z.number()');
    expect(result).toContain('stat_block: ItemStatBlockSchema');
    expect(result).toContain('export type ItemStatBlock = z.infer<typeof ItemStatBlockSchema>;');
  });

  test('generates schema for array of objects', () => {
    const items = [
      {
        id: '1',
        locations: [
          { map: 'map1', x: 10 },
          { map: 'map2', x: 20 },
        ],
      },
    ];

    const result = generateZodSchema('Item', items);

    expect(result).toContain('export const ItemLocationSchema = z.object({');
    expect(result).toContain('map: z.string()');
    expect(result).toContain('x: z.number()');
    expect(result).toContain('locations: z.array(ItemLocationSchema)');
  });

  test('handles nullable fields', () => {
    const items = [
      { id: '1', description: 'text' },
      { id: '2', description: null },
    ];

    const result = generateZodSchema('Item', items);

    expect(result).toContain('description: z.string().nullable()');
  });

  test('returns empty string for empty items', () => {
    const result = generateZodSchema('Item', []);
    expect(result).toBe('');
  });

  test('includes auto-generated header', () => {
    const items = [{ id: '1' }];
    const result = generateZodSchema('Item', items);
    expect(result).toContain('// Auto-generated by @skippy/cache - do not edit manually');
  });
});
